#!/usr/bin/env bash
#
# Interactive setup script for the Knowledge Elicitation Platform.
# Generates .env, starts services, and creates the worker service account.
#
# Usage: make setup  (or: bash scripts/setup.sh)
#
set -euo pipefail

# --- Resolve paths (works regardless of CWD) ---

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

# --- Colors and helpers ---

BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
NC='\033[0m'

info()  { printf "${CYAN}==> %s${NC}\n" "$*"; }
ok()    { printf "${GREEN} ok ${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}warn${NC} %s\n" "$*"; }
fail()  { printf "${RED}fail${NC} %s\n" "$*"; exit 1; }
ask()   { printf "${BOLD}%s${NC} " "$1"; }

prompt() {
    local var_name="$1" prompt_text="$2" default="${3:-}"
    if [ -n "$default" ]; then
        ask "$prompt_text [$default]:"
        read -r value
        eval "$var_name=\"${value:-$default}\""
    else
        ask "$prompt_text:"
        read -r value
        eval "$var_name=\"$value\""
    fi
}

prompt_secret() {
    local var_name="$1" prompt_text="$2" default="${3:-}"
    if [ -n "$default" ]; then
        ask "$prompt_text [$default]:"
        read -rs value
        echo
        eval "$var_name=\"${value:-$default}\""
    else
        ask "$prompt_text:"
        read -rs value
        echo
        eval "$var_name=\"$value\""
    fi
}

confirm() {
    ask "$1 [y/N]:"
    read -r yn
    [[ "$yn" =~ ^[Yy] ]]
}

# --- Preflight checks ---

command -v docker >/dev/null 2>&1 || fail "docker is required but not installed"
command -v curl >/dev/null 2>&1   || fail "curl is required but not installed"
docker compose version >/dev/null 2>&1 || fail "docker compose v2 is required"

if [ -f .env ]; then
    warn ".env already exists"
    if ! confirm "Overwrite it?"; then
        info "Keeping existing .env — skipping configuration"
        SKIP_ENV=true
    fi
fi

# --- Generate .env ---

if [ "${SKIP_ENV:-}" != "true" ]; then
    echo
    printf "${BOLD}%s${NC}\n" "Knowledge Elicitation Platform — Setup"
    printf "${DIM}%s${NC}\n\n" "This will generate your .env and start services."

    # Core secrets (auto-generated)
    JWT_SECRET=$(openssl rand -hex 32)
    DB_PASSWORD=$(openssl rand -hex 16)
    ok "Generated JWT_SECRET and DB_PASSWORD"

    # Google OAuth
    GOOGLE_CLIENT_ID=""
    GOOGLE_CLIENT_SECRET=""
    GOOGLE_REDIRECT_URI=""
    BOOTSTRAP_ADMIN_EMAIL=""

    echo
    if confirm "Configure Google OAuth? (required for production, skip for local dev)"; then
        prompt GOOGLE_CLIENT_ID "Google Client ID"
        prompt_secret GOOGLE_CLIENT_SECRET "Google Client Secret"
        prompt GOOGLE_REDIRECT_URI "OAuth Redirect URI" "https://your-domain.com/auth/callback"
        prompt BOOTSTRAP_ADMIN_EMAIL "Admin email (auto-receives all roles on first login)"
    else
        info "Skipping OAuth — dev login will be available"
    fi

    # Frontend URL / CORS
    echo
    prompt FRONTEND_URL "Frontend URL" "http://localhost:5173"
    if [ "$FRONTEND_URL" = "http://localhost:5173" ]; then
        CORS_ORIGINS='["http://localhost:5173"]'
        DEV_LOGIN_ENABLED="true"
    else
        CORS_ORIGINS="[\"$FRONTEND_URL\"]"
        DEV_LOGIN_ENABLED="true"  # Keep enabled for initial setup; disable later
    fi

    # AI / Worker
    ANTHROPIC_API_KEY=""
    LLM_MODEL="anthropic/claude-sonnet-4-6"
    RECOMMENDATION_STRATEGY="auto"

    echo
    if confirm "Configure AI features? (requires Anthropic API key)"; then
        prompt_secret ANTHROPIC_API_KEY "Anthropic API Key"
        prompt LLM_MODEL "LLM model" "anthropic/claude-sonnet-4-6"
        prompt RECOMMENDATION_STRATEGY "Recommendation strategy (auto/llm/embedding)" "auto"
    else
        info "Skipping AI — worker will start but LLM features will be unavailable"
    fi

    # Embeddings
    EMBEDDING_MODEL=""
    EMBEDDING_API_BASE=""
    EMBEDDING_API_KEY=""
    ENABLE_EMBEDDING=false

    echo
    if confirm "Enable local embedding service? (CPU-only, downloads ~605MB model)"; then
        EMBEDDING_MODEL="openai/bge-m3"
        EMBEDDING_API_BASE="http://embedding:8090/v1/"
        EMBEDDING_API_KEY="no-key"
        ENABLE_EMBEDDING=true
        RECOMMENDATION_STRATEGY="auto"
    fi

    # Slack
    SLACK_BOT_TOKEN=""
    SLACK_DEFAULT_CHANNEL=""

    echo
    if confirm "Configure Slack notifications?"; then
        prompt_secret SLACK_BOT_TOKEN "Slack Bot Token (xoxb-...)"
        prompt SLACK_DEFAULT_CHANNEL "Default Slack channel" "#knowledge-elicitation"
    else
        info "Skipping Slack — no notifications will be sent"
    fi

    # Write .env
    cat > .env << ENVEOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Core
DB_PASSWORD=$DB_PASSWORD
DATABASE_URL=postgresql+asyncpg://app:${DB_PASSWORD}@db:5432/knowledge_elicitation
JWT_SECRET=$JWT_SECRET
DEV_LOGIN_ENABLED=$DEV_LOGIN_ENABLED
CORS_ORIGINS=$CORS_ORIGINS
FRONTEND_URL=$FRONTEND_URL

# Authentication
GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
BOOTSTRAP_ADMIN_EMAIL=$BOOTSTRAP_ADMIN_EMAIL

# Worker / LLM
WORKER_URL=http://worker:8001
WORKER_API_KEY=
LLM_MODEL=$LLM_MODEL
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
RECOMMENDATION_STRATEGY=$RECOMMENDATION_STRATEGY

# Embeddings
EMBEDDING_MODEL=$EMBEDDING_MODEL
EMBEDDING_API_BASE=$EMBEDDING_API_BASE
EMBEDDING_API_KEY=$EMBEDDING_API_KEY

# Slack
SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN
SLACK_DEFAULT_CHANNEL=$SLACK_DEFAULT_CHANNEL
ENVEOF

    ok "Created .env"
fi

# --- Download embedding model (if enabled) ---

if [ "${ENABLE_EMBEDDING:-false}" = "true" ]; then
    echo
    info "Downloading embedding model..."
    make embed-download
fi

# --- Determine dev vs production mode ---

if [ "${FRONTEND_URL:-http://localhost:5173}" != "http://localhost:5173" ]; then
    PRODUCTION=true
    info "Production mode detected (FRONTEND_URL=$FRONTEND_URL)"
else
    PRODUCTION=false
fi

# --- Start services ---

echo
info "Starting services..."
if [ "$PRODUCTION" = "true" ]; then
    if [ "${ENABLE_EMBEDDING:-false}" = "true" ]; then
        docker compose -f docker-compose.yml --profile embedding up -d --build db api worker embedding &
    else
        make up-prod &
    fi
else
    if [ "${ENABLE_EMBEDDING:-false}" = "true" ]; then
        make up-embed &
    else
        make up &
    fi
fi
COMPOSE_PID=$!

# Wait for API to be healthy
info "Waiting for API to be ready..."
TIMEOUT=120
ELAPSED=0
while ! curl -sf http://localhost:8000/health >/dev/null 2>&1; do
    sleep 2
    ELAPSED=$((ELAPSED + 2))
    if [ $ELAPSED -ge $TIMEOUT ]; then
        fail "API did not start within ${TIMEOUT}s. Check: docker compose logs api"
    fi
done
ok "API is healthy"

# --- Create service account ---

echo
info "Creating worker service account..."
API_KEY=$(docker compose exec -T api python scripts/create_service_account.py 2>/dev/null \
    | grep "API Key:" | awk '{print $NF}') || true

if [ -n "$API_KEY" ]; then
    # Update .env with the service account key
    if grep -q "^WORKER_API_KEY=" .env; then
        sed -i.bak "s|^WORKER_API_KEY=.*|WORKER_API_KEY=$API_KEY|" .env && rm -f .env.bak
    fi
    ok "Service account created — WORKER_API_KEY set in .env"

    # Restart to pick up the key
    docker compose restart worker api >/dev/null 2>&1
    ok "Restarted api and worker with service account key"
else
    warn "Could not create service account automatically"
    warn "Run manually: docker compose exec api python scripts/create_service_account.py"
fi

# --- Seed data (optional) ---

echo
if confirm "Seed sample data? (5 users, 5 questions — useful for testing)"; then
    docker compose exec -T api python scripts/seed.py
    ok "Sample data seeded"
fi

# --- Reverse proxy (optional) ---

echo
if confirm "Set up a reverse proxy with TLS? (requires a domain pointed at this server)"; then
    # Extract domain hint from FRONTEND_URL if it's not localhost
    RP_ARGS=()
    if [ "${FRONTEND_URL:-}" != "http://localhost:5173" ] && [ -n "${FRONTEND_URL:-}" ]; then
        RP_DOMAIN=$(echo "$FRONTEND_URL" | sed 's|^https\?://||; s|/.*||; s|:.*||')
        RP_ARGS=(--domain "$RP_DOMAIN")
    fi
    "$SCRIPT_DIR/setup-reverse-proxy.sh" "${RP_ARGS[@]}"
    REVERSE_PROXY_DONE=true
else
    info "Skipping reverse proxy — see docs/deployment.md step 8, or run later:"
    echo "  make setup-reverse-proxy"
fi

# --- Summary ---

echo
printf "${BOLD}%s${NC}\n" "Setup complete!"
echo
echo "Services running:"
echo "  API:       http://localhost:8000/health"
echo "  Frontend:  http://localhost:5173"
echo "  Worker:    http://localhost:8001"
if [ "${ENABLE_EMBEDDING:-false}" = "true" ]; then
echo "  Embedding: http://localhost:8090/health"
fi
echo
if [ "${REVERSE_PROXY_DONE:-}" = "true" ]; then
    echo "Next steps:"
    echo "  1. Open your domain in a browser and sign in"
    echo "  2. Verify all features work over HTTPS"
else
    echo "Next steps:"
    echo "  1. Open http://localhost:5173 and sign in"
    if [ -z "${GOOGLE_CLIENT_ID:-}" ]; then
    echo "     (Dev login is enabled — click 'Sign in as Test User')"
    fi
    echo "  2. Set up a reverse proxy: make setup-reverse-proxy"
    echo "  3. Disable dev login: set DEV_LOGIN_ENABLED=false in .env"
fi
echo
echo "Logs: make logs"
echo "Stop: make down"
